# Generated by Django 6.0.6 on 2026-08-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
