# Generated by Django 6.0.6 on 2026-08-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_student'),
        ('examinations', '0002_alter_mark_student'),
        ('finance', '0002_alter_feepayment_student'),
        ('students', '0002_remove_student_classroom_remove_student_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
