# Generated by Django 6.0.6 on 2026-08-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepayment',
            old_name='last_payment_date',
            new_name='date_paid',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
