# Generated by Django 6.0.6 on 2026-08-26 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_last_payment_date_feepayment_date_paid_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='students.studentprofile'),
        ),
    ]
