# Generated by Django 6.0.6 on 2026-08-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='student',
            name='fees_balance',
            field=models.CharField(default='Ksh 5,000', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='fees_paid',
            field=models.CharField(default='Ksh 45,000', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='t1_bio',
            field=models.CharField(default='A-', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t1_chem',
            field=models.CharField(default='B+', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t1_cre',
            field=models.CharField(default='A-', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t1_eng',
            field=models.CharField(default='A-', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t1_history',
            field=models.CharField(default='B+', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t1_kis',
            field=models.CharField(default='B', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t1_math',
            field=models.CharField(default='B+', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t1_mean',
            field=models.CharField(default='B+ (67 pts)', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='t2_bio',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t2_chem',
            field=models.CharField(default='A-', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t2_cre',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t2_eng',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t2_history',
            field=models.CharField(default='A-', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t2_kis',
            field=models.CharField(default='B+', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t2_math',
            field=models.CharField(default='A-', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t2_mean',
            field=models.CharField(default='A- (72 pts)', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='t3_bio',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t3_chem',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t3_cre',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t3_eng',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t3_history',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t3_kis',
            field=models.CharField(default='A-', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t3_math',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='t3_mean',
            field=models.CharField(default='A (78 pts)', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='adm_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
