# Generated by Django 6.0.6 on 2026-08-25 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], default='Term 1', max_length=20)),
                ('maths', models.IntegerField(default=0)),
                ('english', models.IntegerField(default=0)),
                ('kiswahili', models.IntegerField(default=0)),
                ('chemistry', models.IntegerField(default=0)),
                ('biology', models.IntegerField(default=0)),
                ('maths_grade', models.CharField(blank=True, max_length=2)),
                ('english_grade', models.CharField(blank=True, max_length=2)),
                ('kiswahili_grade', models.CharField(blank=True, max_length=2)),
                ('chemistry_grade', models.CharField(blank=True, max_length=2)),
                ('biology_grade', models.CharField(blank=True, max_length=2)),
                ('mean_score', models.FloatField(blank=True, null=True)),
                ('mean_grade', models.CharField(blank=True, max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
