# Generated by Django 6.0.6 on 2026-08-14 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_classroom_alter_attendance_date'),
        ('students', '0002_remove_student_classroom_remove_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
    ]
